新增index頁面功能
chiderlin/taipei-day-trip-website pull request #3
Opened 2021-04-28 08:12 UTC by chiderlin

林育琦
http://35.73.36.129:3000/

2021-04-28 08:25 UTC, cwpeng requested changes
1200 以上的版面，例如 1920，請把景點列表限制在總寬度 1200 像素左右，以下截圖就是在 1920 的螢幕寬度時，景點列表的寬度超過了 1200 像素。
![35 73 36 129_3000_](https://user-images.githubusercontent.com/6104683/116371773-5d331680-a83e-11eb-8258-e6bf29507d99.png)

2021-04-28 08:54 UTC, chiderlin commented
修改完成~~，地名因為會有卡到第二行的狀況，目前處理方式是把字調小一點，還沒有想到其他的方法
http://35.73.36.129:3000/

2021-04-28 09:12 UTC, cwpeng requested changes
這是 1300 像素寬度左右的螢幕，你的景點列表會變得太小。請仔細確認：螢幕寬度大於 1200 像素的時候，景點列表應該要固定在 1200 像素左右，這個要求。
![35 73 36 129_3000_](https://user-images.githubusercontent.com/6104683/116378537-d03f8b80-a844-11eb-9440-721170b5bad5.png)

2021-04-28 10:50 UTC, chiderlin commented
修改完成
1. 1200像素以上景點列表固定
2. 字的大小可以順利16px了
3. 不幸有換行的景點 改為 ...取代

2021-04-28 14:46 UTC, cwpeng requested changes
主視覺中的文字和搜尋框，左邊要和上面的標題以及下面的景點列表切齊哦 ~
![35 73 36 129_3000_](https://user-images.githubusercontent.com/6104683/116423745-8b7f1900-a873-11eb-810f-7300df08ebad.png)

2021-04-29 03:03 UTC, chiderlin commented
文字和搜尋框對齊 修改完成~

2021-04-29 06:39 UTC, cwpeng commented
看起來是可以了，有需要確認請再發 Review 要求給我 ~

2021-04-29 14:11 UTC, chiderlin commented
中間遇到很多問題(其一如圖:關鍵字搜尋結果偶爾出現重複)，卡了半天一天，才用true flase變數解決了QQ
也微調很多版面的位置哈哈哈(我的commit....)，剛剛完工，現在才看到老師的留言~ 
![image](https://user-images.githubusercontent.com/68468916/116564038-31e02280-a937-11eb-9d92-ffc76254b60f.png)

2021-04-29 15:22 UTC, cwpeng approved these changes
Finally, Good. :)

2021-04-29 15:44 UTC, merged