新增會員功能整合
chiderlin/taipei-day-trip-website pull request #5
Opened 2021-05-11 03:28 UTC by chiderlin

2021-05-11 10:07 UTC, cwpeng requested changes
我按註冊新帳戶會失敗，後端程式會報錯 ~
![未命名-2](https://user-images.githubusercontent.com/6104683/117798398-b14cea80-b283-11eb-93d6-7fb3b85fb672.png)

2021-05-11 11:05 UTC, chiderlin commented
修改好了 請老師看看~ 浪費了一次給老師審核的機會 T_T

2021-05-11 11:51 UTC, cwpeng requested changes
我註冊登入後，按登出系統，重新整理網頁，依然會偵測到登入的狀態，請修正哦

2021-05-12 06:16 UTC, chiderlin commented
請老師試試~
目前有遇到一個問題是 safari案登出會無效，但chrome可以登出，目前一直找不到原因及解決辦法..

2021-05-12 07:24 UTC, cwpeng approved these changes
OK 哦，這樣就沒問題了 :)

2021-05-12 07:43 UTC, merged